---
sidebar: sidebar 
permalink: concept-kubernetes-backup-to-cloud.html 
keywords: backing up, restoring, back up, backup, restore, aws, azure, s3, blob, google cloud, back up volumes, cloud backup, restore volumes, billing, cost, kubernetes 
summary: Cloud Backup は、 Kubernetes クラスタデータを保護し、長期アーカイブするためのバックアップおよびリストア機能を提供します。バックアップは自動的に生成され、パブリックまたはプライベートクラウドアカウントのオブジェクトストアに格納されます。 
---
= Cloud Backup を使用して Kubernetes クラスタのデータを保護
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup は、 Kubernetes クラスタデータを保護し、長期アーカイブするためのバックアップおよびリストア機能を提供します。バックアップは自動的に生成され、パブリックまたはプライベートクラウドアカウントのオブジェクトストアに格納されます。

必要に応じて、バックアップから同じ作業環境または別の作業環境に全面的に _ ボリューム _ をリストアできます。



== の機能

バックアップ機能：

* 永続ボリュームの独立したコピーを低コストのオブジェクトストレージにバックアップできます。
* クラスタ内のすべてのボリュームに単一のバックアップポリシーを適用するか、または一意のリカバリポイント目標が設定されたボリュームに異なるバックアップポリシーを割り当てます。
* バックアップデータは、転送中の AES-256 ビット暗号化と TLS 1.2 HTTPS 接続によって保護されます。
* 単一ボリュームで最大 4 、 000 個のバックアップがサポートされます。


リストア機能：

* 特定の時点からデータをリストアします。
* ボリュームをソースシステムまたは別のシステムにリストアします。
* 元の ACL を維持したまま、指定した場所にデータを直接配置して、ブロックレベルでデータをリストアします。




== サポートされている Kubernetes 作業環境とオブジェクトストレージプロバイダ

Cloud Backup を使用すると、以下の作業環境から以下のパブリックおよびプライベートクラウドプロバイダのオブジェクトストレージに Kubernetes ボリュームをバックアップできます。

[cols="45,40"]
|===
| ソースの作業環境 | バックアップファイルの保存先 


| AWS の Kubernetes クラスタ | Amazon S3 


| Azure の Kubernetes クラスタ | Azure Blob の略 


| Google の Kubernetes クラスタ | Google クラウドストレージ 
|===
Kubernetes バックアップファイルから次の作業環境にボリュームをリストアできます。

[cols="40,45"]
|===
| バックアップファイルの場所 | デスティネーションの作業環境 


| Amazon S3 | AWS の Kubernetes クラスタ 


| Azure Blob の略 | Azure の Kubernetes クラスタ 


| Google クラウドストレージ | Google の Kubernetes クラスタ 
|===


== コスト

Cloud Backup の使用に関連するコストには、リソース料金とサービス料金の 2 種類があります。

* リソース料金 *

クラウド内のオブジェクトストレージの容量については、リソースの料金がクラウドプロバイダに支払われます。クラウドバックアップではソースボリュームの Storage Efficiency が保持されるため、クラウドプロバイダ側で、 data_after_ONTAP 効率化のコストを支払います（重複排除と圧縮が適用されたあとのデータ量が少ないほど）。

* サービス料金 *

サービス料金はネットアップにお支払いいただき、バックアップの作成時とリストア時のコストの両方を負担させていただきます。保護するデータの料金は、オブジェクトストレージにバックアップされるボリュームのソースの使用済み論理容量（ ONTAP 効率化）で計算されます。この容量はフロントエンドテラバイト（ FETB ）とも呼ばれます。

バックアップサービスの料金を支払う方法は 2 つあります。1 つ目は、クラウドプロバイダを利用して月額料金を支払う方法です。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。を参照してください <<Licensing,ライセンス>> 詳細については、を参照してください



== ライセンス

Cloud Backup には、従量課金制（ PAYGO ）とお客様所有のライセンス（ BYOL ）の 2 つのライセンスオプションがあります。ライセンスをお持ちでない場合は、 30 日間の無償トライアルをご利用いただけます。



=== 無償トライアルをご利用ください

30 日間の無償トライアルを使用すると、残りの無料試用日数が通知されます。無償トライアルが終了すると、バックアップは作成されなくなります。サービスを引き続き使用するには、サービスに登録するかライセンスを購入する必要があります。

サービスが無効になってもバックアップファイルは削除されません。バックアップを削除しないかぎり、バックアップで使用する容量のオブジェクトストレージのコストは引き続きクラウドプロバイダから請求されます。



=== 従量課金制のサブスクリプション

Cloud Backup は従量課金制モデルで、使用量に応じたライセンスを提供します。クラウドプロバイダの市場に登録した後は、バックアップされたデータに対して GB 単位の支払いを行います。つまり、前払いによる支払いはありません。クラウドプロバイダから月額料金で請求されます。

無償トライアルを利用されている場合や、お客様が独自のライセンスを使用（ BYOL ）されている場合も、サブスクリプションを設定する必要があります。

* 登録すると、無料トライアルの終了後にサービスが中断されることがなくなります。
+
試用期間が終了すると、バックアップしたデータの量に応じて 1 時間ごとに課金されます。

* BYOL ライセンスで許可されている数を超えるデータをバックアップした場合、データバックアップは従量課金制サブスクリプションを使用して続行されます。
+
たとえば、 10 TB の BYOL ライセンスがある場合、 10 TB を超える容量はすべて、 PAYGO サブスクリプションによって課金されます。



お客様は、無料トライアル期間中、または BYOL ライセンスを超えていない場合は、従量課金制サブスクリプションから料金を請求されることはありません。

link:task-licensing-cloud-backup.html#use-a-cloud-backup-paygo-subscription["従量課金制サブスクリプションの設定方法について説明します"]。



=== お客様所有のライセンスを使用

BYOL は、期間ベース（ 12 カ月、 24 カ月、 36 カ月）の _ と _ の容量ベースで、 1 TB 単位での増分に基づいています。ネットアップに料金を支払って、 1 年分のサービスを使用し、最大容量である 10TB を支払うことになります。

サービスを有効にするために、 Cloud Manager のデジタルウォレットのページに入力したシリアル番号が表示されます。いずれかの制限に達すると、ライセンスを更新する必要があります。Backup BYOL ライセンス環境 では、に関連付けられているすべてのソースシステムがライセンスされます https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html["Cloud Manager アカウント"^]。

link:task-licensing-cloud-backup.html#use-a-cloud-backup-byol-license["BYOL ライセンスの管理方法について説明します"]。



== Cloud Backup の仕組み

Kubernetes システムで Cloud Backup を有効にすると、サービスはデータのフルバックアップを実行します。初期バックアップ後は、追加のバックアップはすべて差分になります。つまり、変更されたブロックと新しいブロックのみがバックアップされます。これにより、ネットワークトラフィックを最小限に抑えることができます。


CAUTION: クラウドプロバイダ環境からバックアップファイルの管理や変更を直接行うと、ファイルが破損してサポートされない構成になる可能性があります。



=== サポートされるストレージクラスまたはアクセス階層

* AWS では、バックアップは _Standard_storage クラスから開始し、 30 日後に _Standard-Infrequent Access_storage クラスに移行します。
* Azure では、バックアップは _COOL アクセス層に関連付けられます。
* GCP では、バックアップはデフォルトで _Standard_storage クラスに関連付けられています。




=== クラスタごとにカスタマイズ可能なバックアップスケジュールと保持設定

作業環境で Cloud Backup を有効にすると、最初に選択したすべてのボリュームが、定義したデフォルトのバックアップポリシーを使用してバックアップされます。Recovery Point Objective （ RPO ；目標復旧時点）が異なるボリュームに対して異なるバックアップポリシーを割り当てる場合は、そのクラスタに追加のポリシーを作成し、そのポリシーを他のボリュームに割り当てることができます。

すべてのボリュームについて、毎時、毎日、毎週、および毎月のバックアップを組み合わせて選択できます。

カテゴリまたは間隔のバックアップの最大数に達すると、古いバックアップは削除されるため、常に最新のバックアップが保持されます。



== サポートされるボリューム

Cloud Backup は永続ボリューム（ PVS ）をサポートしています。



== 制限

* ポリシーにボリュームが割り当てられていない場合にバックアップポリシーを作成または編集するときは、バックアップの保持数を 1018 以下にする必要があります。回避策 では、ポリシーを作成するバックアップの数を減らすことができます。その後、ポリシーを編集して、ポリシーにボリュームを割り当てたあとで最大 4 、 000 個のバックアップを作成できます。
* Kubernetes ボリュームでは、 * 今すぐバックアップ * ボタンを使用したアドホックボリュームのバックアップはサポートされていません。

