---
sidebar: sidebar 
permalink: reference-aws-backup-tiers.html 
keywords: aws, amazon, s3, storage classes, archive 
summary: Cloud Backup は、 2 つの S3 アーカイブストレージクラスとほとんどのリージョンをサポートします。 
---
= AWS S3 アーカイブストレージクラスおよびリストアの読み出し時間
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup は、 2 つの S3 アーカイブストレージクラスとほとんどのリージョンをサポートします。



== Cloud Backup でサポートされている S3 アーカイブストレージクラスです

バックアップファイルが最初に作成されるときは、 S3_Standard_storage に格納されています。この階層は、アクセス頻度の低いデータを格納するために最適化されていますが、すぐにアクセスすることもできます。30 日経過すると、バックアップは S3_Standard - Infrequent Access_storage クラスに移行してコストを削減します。

ソースクラスタで ONTAP 9.10.1 以降が実行されている場合は、特定の日数（通常は 30 日以上）が経過したあとに S3 Glacier Deep Archive_storage にバックアップを階層化して、コストをさらに最適化することができます。これらの階層のデータは、必要なときにすぐにアクセスすることはできず、取得コストが高くなるため、アーカイブされたバックアップファイルからデータをリストアする頻度を考慮する必要があります。についてのセクションを参照してください <<Restoring data from archival storage,アーカイブストレージからのデータのリストア>>。

このタイプのライフサイクルルールでクラウドバックアップを設定する場合は、 AWS アカウントでバケットを設定する際にライフサイクルルールを設定しないでください。

https://aws.amazon.com/s3/storage-classes/["S3 ストレージクラスについて説明します"^]。



== アーカイブストレージからのデータのリストア

古いバックアップファイルをアーカイブストレージに保存すると、標準または標準の IA ストレージよりもはるかに低コストですが、リストア処理のためにアーカイブストレージ内のバックアップファイルからデータにアクセスすると、時間がかかり、コストがかかります。

Amazon S3 Glacier と Amazon S3 Glacier Deep Archive からデータをリストアするのにどれくらいのコストがかかりますか。:: Amazon S3 Glacier からデータを読み出すときは 3 つのリストア優先度を選択でき、 Amazon S3 Glacier Deep Archive からデータを読み出すときは 2 つのリストア優先度を選択できます。S3 Glacier Deep Archive のコストは S3 Glacier よりも低く：
+
--
[cols="25,25,25,25"]
|===
| アーカイブ階層 3+| 優先度とコストを復元します 


|  | * 高 * | * 標準 * | * 低 * 


| * S3 Glacier * | 高速な読み出し、コストの最大化 | 取得速度が低下し、コストが削減されます | 読み出しに時間がかかり、コストを最小限に抑えます 


| * S3 Glacier Deep Archive * |  | 高速な読み出し、コストの増大 | 取得速度が遅く、コストが最も低い 
|===
各メソッドには、 GB 単位の取得料金とリクエストごとの料金が異なります。AWS リージョン別の S3 Glacier の詳細な価格設定については、を参照してください https://aws.amazon.com/s3/pricing/["Amazon S3 の価格設定ページ"^]。

--
Amazon S3 Glacier にアーカイブされているオブジェクトのリストアにはどれくらいの時間がかかりますか。:: リストアの合計時間は、次の 2 つの要素で構成されます。
+
--
* * 取得時間 * ：アーカイブからバックアップファイルを取得して標準ストレージに保存する時間。これは、「水和」時間と呼ばれることもあります。取得時間は、選択したリストア優先度によって異なります。
+
[cols="25,20,20,20"]
|===
| アーカイブ階層 3+| 優先度と取得時間のリストア 


|  | * 高 * | * 標準 * | * 低 * 


| * S3 Glacier * | 3 ～ 5 分 | 3 ～ 5 時間 | 5 ～ 12 時間 


| * S3 Glacier Deep Archive * |  | 12 時間 | 48 時間 
|===
* * リストア時間 * ： Standard ストレージのバックアップファイルからデータをリストアする時間。アーカイブ層を使用しない場合、この時間は標準ストレージから直接実行される通常のリストア処理と同じです。


Amazon S3 Glacier と S3 Glacier Deep Archive の読み出しオプションの詳細については、を参照してください https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["これらのストレージクラスに関する Amazon FAQ"^]。

--

