---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: SQL Server データベースをクラウドからオンプレミスの SnapCenter サーバにリストアできます。 
---
= SQL Server データベースをリストアする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SQL Server データベースは、同じホストまたは代替ホストにリストアできます。ログバックアップのリカバリおよび可用性グループの再シードはサポートされていません。

* 手順 *

. Cloud Manager UI で、 * Backup & Restore * > * Applications * の順にクリックします。
. [ * フィルター条件 * ] フィールドで、フィルター * タイプ * を選択し、ドロップダウンから * SQL* を選択します。
. 「 * 詳細表示 * 」をクリックすると、使用可能なすべてのバックアップが表示されます。
. バックアップを選択し、 * リストア * をクリックします。
. データベースファイルのリストア先を選択します。
+
|===
| オプション | 説明 


 a| 
バックアップが作成されたホストにデータベースをリストアします
 a| 
バックアップを作成した SQL Server にデータベースをリストアする場合は、このオプションを選択します。



 a| 
データベースを代替ホストにリストアします
 a| 
バックアップを作成したホストと同じまたは別のホストの別の SQL Server にデータベースをリストアする場合は、このオプションを選択します。

ホスト名を選択し、データベース名を指定し（オプション）、インスタンスを選択し、リストアパスを指定します。


NOTE: 代替パスに指定するファイル拡張子は、元のデータベースファイルのファイル拡張子と同じにする必要があります。

[ リストア範囲 ] ページに [ データベースを別のホストにリストアする *] オプションが表示されない場合は、ブラウザキャッシュをクリアします。

|===
. [* リストア前オプション * ] ページで、次のいずれかのオプションを選択します。
+
** [ リストア時に同じ名前でデータベースを上書きする ] を選択して、同じ名前でデータベースをリストアします。
** データベースをリストアし、既存のレプリケーション設定を保持するには、「 * SQL データベースのレプリケーション設定を保持 * 」を選択します。


. [ リストア後のオプション *] ページで、追加のトランザクションログをリストアするためのデータベース状態を指定するには、次のいずれかのオプションを選択します。
+
** 必要なすべてのバックアップを今すぐリストアする場合は、 [* Operational 、 but unavailable] を選択します。
+
これはデフォルトの動作で、コミットされていないトランザクションをロールバックすることでデータベースを使用可能な状態にします。バックアップを作成するまで追加のトランザクションログはリストアできません。

** コミットされていないトランザクションをロールバックせずにデータベースを非稼働状態のままにするには、 [*Non-operational, but available*] を選択します。
+
追加のトランザクションログをリストアできます。データベースはリカバリされるまで使用できません。

** データベースを読み取り専用モードのままにするには、「 * 読み取り専用モード」と「使用可能 * 」を選択します。
+
コミットされていないトランザクションはロールバックされますが、ロールバックされた操作がスタンバイファイルに保存されるため、リカバリ前の状態に戻すことができます。

+
[ ディレクトリを元に戻す ] オプションが有効になっている場合は、さらに多くのトランザクションログがリストアされます。トランザクションログのリストア処理が失敗した場合は、変更をロールバックできます。詳細については、 SQL Server のマニュアルを参照してください。



. 詳細を確認して、 * リストア * をクリックします。

