---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: Oracle データベースをクラウドからオンプレミスの SnapCenter サーバにリストアできます。 
---
= Oracle データベースをリストアします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle データベースは、同じ SnapCenter サーバホスト、同じ SVM 、または同じデータベースホストにのみリストアできます。RAC データベースの場合は、バックアップが作成されたオンプレミスノードにデータがリストアされます。

制御ファイルのリストアを含むフルデータベースのみがサポートされます。アーカイブログが AFS 内にない場合は、リカバリに必要なアーカイブログが格納されている場所を指定する必要があります。

* 手順 *

. Cloud Manager UI で、 * Backup & Restore * > * Applications * の順にクリックします。
. [ * フィルター条件 * ] フィールドで、フィルター * タイプ * を選択し、ドロップダウンから [* Oracle* ] を選択します。
. リストアするデータベースに対応する *View Details* をクリックし、 *Restore* をクリックします。
. [ リストアタイプ ] ページで、次の操作を実行します。
+
.. 制御ファイルとフルデータベースをリストアする場合は、「 * 制御ファイル」を選択します。
.. リストアとリカバリに必要な場合は、「 * データベースの状態を変更」を選択して、データベースの状態をリストアとリカバリ処理の実行に必要な状態に変更します。
+
データベースの状態は、高いレベルから順に、オープン、マウント済み、開始、シャットダウンがあります。リストア処理を実行するために、データベースの状態を高いレベルから低いレベルに変更する必要がある場合は、このチェックボックスをオンにします。リストア処理を実行するために、データベースの状態を低いレベルから高いレベルに変更する必要がある場合は、このチェックボックスをオンにしなくても自動的に状態が変更されます。

+
データベースが OPEN 状態で、リストアのためにデータベースが MOUNTED 状態である必要がある場合、データベースの状態はこのチェックボックスをオンにした場合にのみ変更されます。



. Recovery Scope ページで、次のアクションを実行します。
+
.. リカバリの範囲を指定します。
+
|===
| 状況 | 手順 


 a| 
最後のトランザクションまでリカバリする場合
 a| 
[ * すべてのログ * ] を選択します。



 a| 
特定の System Change Number （ SCN ）までリカバリする場合
 a| 
[* Until SCN （ System Change Number ） ] を選択します。



 a| 
特定の日時までリカバリする必要がある
 a| 
[ * 日付と時刻 * ] を選択します。

データベースホストのタイムゾーンの日付と時刻を指定する必要があります。



 a| 
リカバリが不要である場合
 a| 
「 * リカバリなし * 」を選択します。



 a| 
外部アーカイブログの場所を指定する
 a| 
アーカイブログが AFS 内にない場合は、リカバリに必要なアーカイブログが格納されている場所を指定する必要があります。

|===
.. リカバリ後にデータベースを開く場合は、チェックボックスを選択します。
+
RAC セットアップでは、リカバリに使用される RAC インスタンスのみがリカバリ後に開きます。



. 詳細を確認して、 * リストア * をクリックします。

